global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'my-computer-monitor'
    metrics_path: 'http://localhost:9100/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

